SET(CMAKE_C_COMPILER /media/pavel/android/standalone-toolchains/android-14/arm/bin/arm-linux-androideabi-gcc-4.6.3)
SET(CMAKE_CXX_COMPILER /media/pavel/android/standalone-toolchains/android-14/arm/bin/arm-linux-androideabi-g++)
SET(CMAKE_FIND_ROOT_PATH /media/pavel/android/standalone-toolchains/android-14/arm/ /media/pavel/android/standalone-toolchains/android-14/arm/arm-linux-androideabi/ /media/pavel/android/standalone-toolchains/android-14/arm/sysroot/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
